# Generated by Django 5.0.1 on 2024-06-13 14:49

import store.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image_alter_product_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=store.storage.NonLockingFileSystemStorage(), upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, storage=store.storage.NonLockingFileSystemStorage(), upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, storage=store.storage.NonLockingFileSystemStorage(), upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, storage=store.storage.NonLockingFileSystemStorage(), upload_to='product_images/'),
        ),
    ]
